=== TomCaserta/QuickbooksOSR/web/osr_docs/html/docexceptions.dtd
<!--   $Id: docexceptions.dtd,v 1.3 2002/07/09 18:22:52 jwortman Exp $    -->
<!--                                                           -->
<!--   docexceptions.dtd                                       -->
<!--   Jennifer Wortman, June 2002                             -->
<!--                                                           -->
<!--   This is the DTD for the Exceptions xml file used        -->
<!--   by docgen to determine which links to element           -->
<!--   and aggregate descriptions should be exceptions         -->
<!--   to the default format.                                  -->
<!--                                                           -->

<!-- Top level -->
<!ELEMENT DocExceptions ((ElementException | AggregateException | AttributeException)+)>

<!-- ElementException must contain an Element plus either one Aggregate, -->
<!-- one Product, or one Aggregate and one Product -->
<!ELEMENT ElementException (Element, ((Aggregate, (Product*)) | Product))>

<!-- AggregateException must contain both Aggregate and Product -->
<!ELEMENT AggregateException (Aggregate, Product)>

<!-- AttributeException must contain an Attribute and a Product -->
<!ELEMENT AttributeException (Attribute, Product)>

<!-- Attribute, Element, Product, and Aggregate are the three lowest level elements -->
<!ELEMENT Attribute (#PCDATA)>
<!ELEMENT Element (#PCDATA)>
<!ELEMENT Aggregate (#PCDATA)>
<!ELEMENT Product (#PCDATA)>

=== TomCaserta/QuickbooksOSR/web/html/ORTexceptions.xml
<?xml version="1.0" ?>
<!DOCTYPE DocExceptions SYSTEM "docexceptions.dtd">
<DocExceptions>


<!--====================-->
<!--	SSN element   	    -->
<!--====================-->
	<ElementException>
		<Element>SSN</Element>
		<Aggregate>Employee</Aggregate>
	</ElementException>

<!--====================-->
<!--	IsManuallyClosed element   	    -->
<!--====================-->
	<ElementException>
		<Element>IsManuallyClosed</Element>
		<Aggregate>SalesOrderLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>IsManuallyClosed</Element>
		<Aggregate>SalesOrder</Aggregate>
	</ElementException>
	<ElementException>
		<Element>IsManuallyClosed</Element>
		<Aggregate>PurchaseOrderLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>IsManuallyClosed</Element>
		<Aggregate>PurchaseOrder</Aggregate>
	</ElementException>

<!--====================-->
<!--	OwnerID element	-->
<!--====================-->
	<ElementException>
		<Element>OwnerID</Element>
		<Aggregate>DataExt</Aggregate>
	</ElementException>
	<ElementException>
		<Element>OwnerID</Element>
		<Aggregate>DataExtDef</Aggregate>
	</ElementException>

<!--====================-->
<!--	Amount element	-->
<!--====================-->
	<ElementException>
		<Element>Amount</Element>
		<Aggregate>Check</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Amount</Element>
		<Aggregate>TotalBalanceFilter</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Amount</Element>
		<Aggregate>CreditCardCredit</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Amount</Element>
		<Aggregate>CreditCardCharge</Aggregate>
	</ElementException>
	
<!--====================-->
<!--	Balance element	-->	
<!--====================-->
	<ElementException>
		<Element>Balance</Element>
		<Aggregate>Vendor</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Balance</Element>
		<Aggregate>Customer</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Balance</Element>
		<Aggregate>Account</Aggregate>
	</ElementException>
	
<!--====================-->
<!--	AppliedAmount element	-->
<!--====================-->
	<ElementException>
		<Element>AppliedAmount</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>
	<ElementException>
		<Element>AppliedAmount</Element>
		<Aggregate>PaymentLine</Aggregate>
	</ElementException>

<!--====================-->
<!--	Cost element	-->
<!--====================-->
	<ElementException>
		<Element>Cost</Element>
		<Aggregate>Check</Aggregate>
	</ElementException>

<!--====================-->
<!--	Desc element	-->
<!--====================-->
	<ElementException>
		<Element>Desc</Element>
		<Aggregate>PurchaseOrderLineGroup</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Desc</Element>
		<Aggregate>PurchaseOrderLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Desc</Element>
		<Aggregate>SalesTaxCode</Aggregate>
	</ElementException>

<!--====================-->
<!--	DiscountPct element	-->
<!--====================-->
	<ElementException>
		<Element>DiscountPct</Element>
		<Aggregate>DateDrivenTerms</Aggregate>
	</ElementException>
	<ElementException>
		<Element>DiscountPct</Element>
		<Aggregate>StandardTerms</Aggregate>
	</ElementException>

<!--====================-->
<!--	DueDate element	-->
<!--====================-->
	<ElementException>
		<Element>DueDate</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>
	<ElementException>
		<Element>DueDate</Element>
		<Aggregate>SalesReceipt</Aggregate>
	</ElementException>

<!--====================-->
<!--	IsPending element	-->
<!--====================-->
	<ElementException>
		<Element>IsPending</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>	
	<ElementException>
		<Element>IsPending</Element>
		<Aggregate>SalesReceipt</Aggregate>
	</ElementException>	
	<ElementException>
		<Element>IsPending</Element>
		<Aggregate>CreditMemo</Aggregate>
	</ElementException>

<!--====================-->
<!--	DueDate element	-->
<!--====================-->
	<ElementException>
		<Element>DueDate</Element>
		<Aggregate>BillToPay</Aggregate>
	</ElementException>		

<!--====================-->
<!--	Memo element ... 11 exceptions	-->
<!--====================-->
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>DepositLine</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>ExpenseLine</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>CreditMemo</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>ReceivePayment</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>Check</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>Bill</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>VendorCredit</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>Estimate</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>PurchaseOrder</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Memo</Element>
		<Aggregate>SalesReceipt</Aggregate>
	</ElementException>
	
<!--====================-->
<!--	Name element	-->
<!--====================-->
	<ElementException>
		<Element>Name</Element>
		<Aggregate>SalesTaxCode</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Name</Element>
		<Aggregate>NameFilter</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Name</Element>
		<Aggregate>Class</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Name</Element>
		<Aggregate>Employee</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>Name</Element>
		<Aggregate>PayrollItemWage</Aggregate>
	</ElementException>		

<!--====================-->
<!--	OpenBalance element	-->
<!--====================-->
	<ElementException>
		<Element>OpenBalance</Element>
		<Aggregate>Account</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>OpenBalance</Element>
		<Aggregate>Customer</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>OpenBalance</Element>
		<Aggregate>Vendor</Aggregate>
	</ElementException>		
		
<!--====================-->
<!--	OpenBalanceDate element	-->
<!--====================-->
	<ElementException>
		<Element>OpenBalanceDate</Element>
		<Aggregate>Account</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>OpenBalanceDate</Element>
		<Aggregate>Customer</Aggregate>
	</ElementException>		
	<ElementException>
		<Element>OpenBalanceDate</Element>
		<Aggregate>Vendor</Aggregate>
	</ElementException>	
	
<!--====================-->
<!--	State element	-->
<!--====================-->
	<ElementException>
		<Element>State</Element>
		<Aggregate>EmployeeAddress</Aggregate>
	</ElementException>			

<!--====================-->
<!--	TxnDate element	-->
<!--====================-->
	<ElementException>
		<Element>TxnDate</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>TxnDate</Element>
		<Aggregate>Check</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>TxnDate</Element>
		<Aggregate>SalesReceipt</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>TxnDate</Element>
		<Aggregate>CreditCardCharge</Aggregate>
	</ElementException>			

<!--====================-->
<!--	TotalBalance element	-->
<!--====================-->
	<ElementException>
		<Element>TotalBalance</Element>
		<Aggregate>Customer</Aggregate>
	</ElementException>			

<!--====================-->
<!--	PurchaseDesc element	-->
<!--====================-->
	<ElementException>
		<Element>PurchaseDesc</Element>
		<Aggregate>ItemInventory</Aggregate>
	</ElementException>			
			
<!--====================-->
<!--	Rate element	-->
<!--====================-->
<!--	Rate exceptions for desktop QB.	(These two have identical text.)	-->
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>TimeTracking</Aggregate>
		<Product>QBD</Product>
	</ElementException>
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>TimeTracking</Aggregate>
		<Product>QBC</Product>
	</ElementException>

<!--	Rate exception for QBOE	--> 
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>TimeTracking</Aggregate>
		<Product>QBO</Product>
	</ElementException>

<!--	Product-independent Rate exceptions.	-->
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>CreditMemoLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>InvoiceLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>EstimateLine</Aggregate>
	</ElementException>
	<ElementException>
		<Element>Rate</Element>
		<Aggregate>PurchaseOrderLine</Aggregate>
	</ElementException>
		<ElementException>
		<Element>Rate</Element>
		<Aggregate>SalesOrderLine</Aggregate>
	</ElementException>
		<ElementException>
		<Element>Rate</Element>
		<Aggregate>SalesReceiptLine</Aggregate>
	</ElementException>

<!--====================-->
<!--	Subtotal element	-->
<!--====================-->
	<ElementException>
		<Element>Subtotal</Element>
		<Aggregate>CreditMemo</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>Subtotal</Element>
		<Aggregate>Invoice</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>Subtotal</Element>
		<Aggregate>Estimate</Aggregate>
	</ElementException>			
	<ElementException>
		<Element>Subtotal</Element>
		<Aggregate>SalesReceipt</Aggregate>
	</ElementException>			

<!--====================-->
<!--	EmployeeAddress aggregate	-->
<!--====================-->
	<AggregateException>
		<Aggregate>EmployeeAddress</Aggregate>
		<Product>QBD</Product>
	</AggregateException>
	<AggregateException>
